import type { Metadata } from "next";
import { Header } from "@/shared/components";
import { Suspense } from "react";


export const metadata: Metadata = {
	title: "Your IceCream Shop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<main className="min-h-screen">
			<Suspense>
				<Header />
			</Suspense>

			{modal}
			{children}
		</main>


	);
}

